// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8KryzdICxSzGZxDf4LNU3XObuA_frPs',
    appId: '1:184088838294:web:250dd9c6daa84bba8582b7',
    messagingSenderId: '184088838294',
    projectId: 'refugee-queue',
    authDomain: 'refugee-queue.firebaseapp.com',
    storageBucket: 'refugee-queue.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoh81xsRyz2QbhgcWtCGjQOrVVU1qiodo',
    appId: '1:184088838294:android:9e0d2375fe74fb748582b7',
    messagingSenderId: '184088838294',
    projectId: 'refugee-queue',
    storageBucket: 'refugee-queue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtdezweWlnj1Bphvlw9GDnwbBiaXhyqco',
    appId: '1:184088838294:ios:9b0407aa74e3bcb88582b7',
    messagingSenderId: '184088838294',
    projectId: 'refugee-queue',
    storageBucket: 'refugee-queue.firebasestorage.app',
    iosBundleId: 'com.example.refQeueu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtdezweWlnj1Bphvlw9GDnwbBiaXhyqco',
    appId: '1:184088838294:ios:9b0407aa74e3bcb88582b7',
    messagingSenderId: '184088838294',
    projectId: 'refugee-queue',
    storageBucket: 'refugee-queue.firebasestorage.app',
    iosBundleId: 'com.example.refQeueu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc8KryzdICxSzGZxDf4LNU3XObuA_frPs',
    appId: '1:184088838294:web:e5ecde76270ed7688582b7',
    messagingSenderId: '184088838294',
    projectId: 'refugee-queue',
    authDomain: 'refugee-queue.firebaseapp.com',
    storageBucket: 'refugee-queue.firebasestorage.app',
  );
}
